#!/bin/sh

# Some config, and initialization
grabboxHome=~/.gnome-grabbox
screenshotsFolder=~/Dropbox/Public/screenshots
mkdir -p $screenshotsFolder

# Prettify notification
iconPath=$grabboxHome/img/dropboxstatus-idle.png
notifyMsg="Capture and upload ready! Picture url is: "

# Generate a random filename, and build it's full path
randFileName=$( < /dev/urandom tr -dc A-Za-z0-9 | head -c8 )
path=$screenshotsFolder/$randFileName.png

# Take the screenshot
gnome-screenshot -a -f $path

# If the screenshot was cancelled, do nothing
if [ ! -e $path ]; then
    exit 0
fi

# Wait for dropbox to finish the upload
until [ "$dropboxStatus" = 'Idle' ]; do
    # Checking the status of dropbox
    dropboxStatus=$(~/bin/dropbox.py status 2>/dev/null)
done

# Get the public url of the screenshot, we've just uploaded
url=$(~/bin/dropbox.py puburl $path)

# Shorten it with google urlshortener
shortenedUrl=$(curl "https://www.googleapis.com/urlshortener/v1/url" -H 'Content-Type: application/json' -d '{"longUrl": "'$url'"}' | jq '.id' | sed -e 's/"//g')

# Clean up
rm $grabboxHome/tmp

# Copy to clipboard
echo $shortenedUrl | xclip -selection clipboard

# And send a notification
notify-send -i $iconPath -t 100 -h int:transient:1 "$notifyMsg$shortenedUrl"
