#!/bin/sh

# Some config, and initialization
grabboxHome=~/.gnome-grabbox
screenshotsFolder=~/Dropbox/Public/screenshots
mkdir -p $screenshotsFolder

# Prettify notification
iconPath=$grabboxHome/img/dropboxstatus-idle.png
notifyMsg="Capture and upload ready! Picture url is: "

# Generate a random filename, and build it's full path
randFileName=$( < /dev/urandom tr -dc A-Za-z0-9 | head -c8 )
path=$screenshotsFolder/$randFileName.png

# Take the screenshot
gnome-screenshot -a -f $path

# Wait for dropbox to finish the upload
until [ "$dropboxStatus" = 'Idle' ]; do
    # Checking the status of dropbox
    dropboxStatus=$(~/bin/dropbox.py status 2>/dev/null)
done

# Get the public url of the screenshot, we've just uploaded
url=$(~/bin/dropbox.py puburl $path)

# Shorten it with google urlshortener
curl "https://www.googleapis.com/urlshortener/v1/url" -H 'Content-Type: application/json' -d '{"longUrl": "'$url'"}' 1>$grabboxHome/tmp 2>/dev/null
shortenedUrl=$(cat $grabboxHome/tmp | awk '/id/' | sed -e 's/http\:/http|/g' | cut -d ':' -f 2 | sed -e 's/[ ",]//g' -e 's/|/:/g') 

# Copy to clipboard
echo $shortenedUrl | xclip -selection clipboard

# Clean up
rm $grabboxHome/tmp

# And send a notification
notify-send -i $iconPath -t 100 -h int:transient:1 "$notifyMsg$shortenedUrl"
